name: ESP-IDF CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp-idf-version: 'release/v4.4'
        
    - name: Build ESP-IDF Project
      run: |
        idf.py build
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: build/*.bin
        
  flash:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp-idf-version: 'release/v5.2.2'
        
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: firmware
        
    - name: Flash ESP-IDF Project
      env:
        ESPPORT: /dev/ttyUSB0
      run: |
        idf.py -p $ESPPORT flash
