name: Build ESP-IDF Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Blink_LED  # Set the default working directory

    steps:
    - uses: actions/checkout@v3

    - name: Install ESP-IDF
      run: |
        mkdir -p ~/esp
        cd ~/esp
        git clone --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        git checkout v5.2.2
        ./install.sh

    - name: Set up environment
      run: |
        . $HOME/esp/esp-idf/export.sh
        idf.py set-target esp32

    - name: Build project
      run: |
        . $HOME/esp/esp-idf/export.sh
        idf.py build

    - name: Print build output
      run: idf.py build | cat